### PR TITLE
add timedwait function

### PR DESCRIPTION
**Pull request by thillux**

### CODE REVIEW

**Comment by thillux** [comment]
I have only tested this on Linux. Windows support was added by guessing parameter types. Please test, if you have Windows available.

**Comment by Evian-Zhang** [comment]
Thank you for your contribution!

For Windows target, `Duration` is not included in the scope. Please import it to make it compile for Windows.

**Comment by thillux** [comment]
I set myself up a working toolchain on windows and also found, that I have to change i32 -> u32. Fix for this was added to this PR.

**Comment by Evian-Zhang** [comment]
Thank you :)

**Pull request merged**
